services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    entrypoint: ["/bin/sh", "/entrypoint.sh"]
    command: []
    runtime: nvidia
    gpus: all
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
      - ./entrypoint.sh:/entrypoint.sh:ro
    environment:
      OLLAMA_NUM_PARALLEL: "1"
      OLLAMA_MAX_LOADED_MODELS: "1"
      OLLAMA_KEEP_ALIVE: "24h"
      NVIDIA_VISIBLE_DEVICES: "all"
      NVIDIA_DRIVER_CAPABILITIES: "compute,utility"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    depends_on:
      - ollama
    ports:
      - "5678:5678"
    environment:
      OLLAMA_BASE_URL: "http://ollama:11434"
    volumes:
      - n8n_data:/home/node/.n8n
    restart: unless-stopped

  fastapi:
    build: ./app
    container_name: fastapi
    depends_on:
      - ollama
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    ports:
      - "8000:8000"
    environment:
      OLLAMA_BASE_URL: "http://ollama:11434"
    volumes:
      - fastapi_data:/app/data
      - ./app:/app/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

volumes:
  ollama_data:
    name: ollama_data
  n8n_data:
    name: n8n_data
  fastapi_data:
    name: fastapi_data
